#ifndef __myFrame__
#define __myFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "wxApp.h"

//// end generated include

/** Implementing MainFrame */
class MyFrame : public MainFrame
{
	public:
		/** Constructor */
		MyFrame( wxWindow* parent );
	//// end generated class members

};

#endif // __myFrame__
